### ISSUE TITLE
【質問】私のリポジトリ"payways"のforkに関して

### ISSUE THREAD

**Issue by Teppeichang** [OguraShota/furima-32084#12]
はじめまして。 表題のリポジトリ作成者の鳥居です。 早速で恐縮ですが一点お聞きしたいことがございます。 テックキャンプ受講生でポートフォリオ作成中と見受けますが、私のリポジトリをforkされた意図は何でしょうか？

**Comment by OguraShota** [comment]
鳥居さんはじめまして。ポートフォリオ作成にあたり現在中身を考えているところなのですが、その際勝手ながら鳥居さんのアプリを拝見させて頂いていました。
forkという物が何かすら分からず、私としてはコードを見ていただけのつもりでしたが、もし余計な事をして作品に影響を与えてしまったとしたら本当に申し訳ございません。

**Comment by Teppeichang** [comment]
ご参考にしていただきありがとうございます。

コードを参考にしていただくならcloneで良いかと思います。
とりあえずforkの解除をお願いします。少し厳しい言い方で恐縮なのですが、何も意味がわからない操作を意味がわからないままやるのは控えましょう。あなたがそれをやられたらどう思うかです。

fork解除後、ご連絡ください。
よろしくお願い致します。

**Comment by OguraShota** [comment]
おっしゃる通りです、以後気を付けます。
fork解除しました、お手数ですがご確認宜しくお願いします。

**Comment by Teppeichang** [comment]
迅速にご対応いただきありがとうございます。
それでは失礼致します。
